# Leen alharbi
-----------------
day6-lab1-numpy

In [66]:
import numpy as np

In [139]:
x = np.array([1,1,1])
y = np.array([0,0,0])

In [140]:
x+y

array([1, 1, 1])

In [141]:
np.add(x,y)

array([1, 1, 1])

In [142]:
x.dtype

dtype('int64')

In [143]:
x.shape

(3,)

In [144]:
x.size

3

In [145]:
x.ndim

1

In [146]:
w = np.array([[12,14,16],[11,13,15]])
w

array([[12, 14, 16],
       [11, 13, 15]])

In [147]:
z =np.arange(1, 4)
z

array([1, 2, 3])

In [148]:
Array=np.vstack((z, w))
newArray = Array.copy()
newArray

array([[ 1,  2,  3],
       [12, 14, 16],
       [11, 13, 15]])

In [149]:
for item in newArray.flat:
    print(item)

1
2
3
12
14
16
11
13
15


In [150]:
newArray.transpose()

array([[ 1, 12, 11],
       [ 2, 14, 13],
       [ 3, 16, 15]])

In [151]:
newArray -= 1
newArray

array([[ 0,  1,  2],
       [11, 13, 15],
       [10, 12, 14]])

In [152]:
newArray.min()

0

In [153]:
newArray.max()

15

In [154]:
newArray[0]

array([0, 1, 2])

In [155]:
newArray[1, 1]

13

In [156]:
newArray[0,1:2] 

array([1])

In [165]:
newArray[2,2:3] 

array([], dtype=int64)

In [166]:
newArray

array([[ 0],
       [ 1],
       [ 2],
       [11],
       [13],
       [15],
       [10],
       [12],
       [14]])

In [167]:
newArray = newArray.reshape(9,1)
newArray

array([[ 0],
       [ 1],
       [ 2],
       [11],
       [13],
       [15],
       [10],
       [12],
       [14]])

In [169]:
newArray 

array([[ 0],
       [ 1],
       [ 2],
       [11],
       [13],
       [15],
       [10],
       [12],
       [14]])

In [ ]:
newArray = newArray.reshape(3,2)
newArray